### ISSUE TITLE
vmpooler throwing exceptions

### ISSUE THREAD

**Issue by timidri** [puppetlabs/vmpooler#129]
Hi,

We have problems using vmpooler.

Symptoms are best explained with this code snippet (exception handling code added by me):

``` ruby
begin
  vm[vm['template']] = $vsphere[vm['template']].find_folder(templatefolders.join('/')).find(vm['template'])
rescue Exception => e
  $logger.log('d', "exception caught, class: #{e.class} description: #{e.backtrace.inspect} ")
end
```

The following exception is thrown: 

```
Exception caught, class: NoMethodError description: ["/root/vmpooler/lib/vmpooler/pool_manager.rb:181:in `block in clone_vm'"]
```

The object $vsphere[vm['template']] actually was nil during execution, so method calls on that object failed. We found that out by adding exception handling code to the call (would be a good idea to add that for all API calls IMHO).

See https://gist.github.com/tvlieg/d2f65c45e1ea63e3f77f for our diffs. Hence the 'helper' object I am creating. Not sure why the API object is nil and whether that is connected to 8 VMs being (re)created simultaneously despite a poolsize of 1...

Our vmpooler.yaml:

``` yaml
:vsphere:
  server: 'swuhtv021.it.mgt'
  username: 'IT\srvcVMpooler'
  password: '<password>'

:redis:
  server : 'localhost'

:config:
  site_name: 'vmpooler'
  logfile: '/var/log/vmpooler.log'
  task_limit: 10
  timeout: 15
  vm_checktime: 15
  vm_lifetime: 24
  vm_lifetime_auth: 24


:graphite:
  server : ''

:pools:
  - name: 'centos-6-x64'
    template: 'Template/TLRHEL6B114R2'
    folder: 'PuppetModuleTests/centos-6-x64'
    clone_target: 'CT2_V0_S01_Y_01'
    pool: 'CT2_V0_S01_Y_01'
    datastore: 'CT2_NFS_Y_N_01_01'
    size: 3
    timeout: 15
    ready_ttl: 1440
```

**Comment by sschneid** [comment]
> The object `$vsphere[vm['template']]` actually was `nil` during execution, so method calls on that object failed.

This is strange.  I added your exception-handling code, as well as a simple dump of the `$vsphere[vm['template']]` object:

````ruby
begin
  vm[vm['template']] = $vsphere[vm['template']].find_folder(templatefolders.join('/')).find(vm['template'])
  puts vm[vm['template']].to_yaml
rescue Exception => e
````

What should be returned here is a `RbVmomi::VIM::VirtualMachine` object.  A (snipped) of the console output:

````yaml
--- !ruby/object:RbVmomi::VIM::VirtualMachine
connection: &1 !ruby/object:RbVmomi::VIM
  deserializer: !ruby/object:RbVmomi::OldDeserializer
    conn: *1
  opts:
    :host: vmware.company.com
    :user: vmware-username
    :password: vmware-password
    :ssl: true
  http: !ruby/object:Net::HTTP
    address: vmware.company.com
    compression:
    verify_callback:
    no_keepalive_server: false
  rev: '5.0'
  ns: urn:vim25
  profile: {}
  serviceContent: !ruby/object:RbVmomi::VIM::ServiceContent
    props:
      :dynamicProperty: []
      :rootFolder: !ruby/object:RbVmomi::VIM::Folder
        connection: *1
        soap: *1
        ref: group-d1
      :propertyCollector: !ruby/object:RbVmomi::VIM::PropertyCollector
        connection: *1
        soap: *1
        ref: propertyCollector
  lock: !ruby/object:Mutex {}
  debug: false
  profiling: false
soap: *1
ref: vm-503722
````

Since you're never getting this far, I'd like to inspect some of the objects being used to create `vm[vm['template']]`.  Can you a debug line:

````ruby
if templatefolders
  puts $vsphere[vm['template']].to_yaml
  begin
    vm[vm['template']] = $vsphere[vm['template']].find_folder(templatefolders.join('/')).find(vm['template'])
````

...and tell me what you see on the console?  Is `$vsphere[vm['template']].to_yaml` defined?

I'd say back out your other patch for now; it looks like it's creating a new `Vmpooler::VsphereHelper` object thread at the start of every clone task, which is probably why you're seeing the simultaneous behavior.
